package.json, src/components/DatasetDownloads/datasetdownloads.test.jsx, src/components/DatasetDownloads/index.jsx, src/components/DatasetTags/datasettags.test.jsx, src/components/DatasetTags/index.jsx, src/index.js, src/styles/scss/components/dataset-tags.scss, src/styles/scss/components/index.scss, src/styles/scss/index.scss, src/templates/Dataset/index.jsx
This PR creates two new components for the Download block and Tag block on the Dataset page. Each component now has more styling and basic tests.
=> Add SCSS as export along with Download and Tag components for Dataset page

package.json, src/components/DatasetAdditionalInformation/index.jsx, src/components/DatasetTags/index.jsx, src/components/TransformedDate/index.jsx, src/styles/scss/components/additional-information-table.scss, src/styles/scss/components/index.scss, src/templates/Dataset/index.jsx
This adds a CMS Design system table for the additional information section of the dataset page. It uses a basic table since there is no need for all the features of a data preview and it's only 2 columns.
=> Dataset Additional Information Table

package.json, src/templates/APIPage/index.jsx
Instead of always hiding the authentication part of the api docs, there is now a prop to opt out of it.
=> Hide auth with prop on API page

src/components/Breadcrumb/index.jsx
updated breadcrumb to not print current page if empty string is passed.
=> WCMS-4632 

src/components/TransformedDate/index.jsx, src/templates/Dataset/DatasetBody.jsx
This is done because we are assuming that Drupal is handling all timezone implications before the string gets sent to us via the API.
=> WCMS-4890: set timezone to UTC to avoid conversions.

src/components/DatasetDownloads/index.jsx, src/templates/Dataset/DatasetBody.jsx
The DatasetBody page would break if there wasn't a data.format in a distribution when `.toUpperCase()` was run against undefined. This replaces it and also removes that method from the download component as well.
=> Add check for mediaType if no file format on dataset

src/components/DatasetAdditionalInformation/index.jsx
Adds a new row to Additional Info table for the related documents that may exist on a dataset.
=> Add Related Documents to dataset additional info table

src/templates/Footer/index.jsx
The structure for the social media links in the footer had url/title as keys in the specific link. This pr updates the render code to match that by checking for a url and then conditionally setting the title and text of the link.
=> Fix [object object] error in footer social media links

src/templates/header/index.jsx
On sites with multiple sub nav menus, the search button on the top right was being pushed down a row on desktop view.
=> Reduce margin a bit on hader to stop wrapping on open payments

src/components/ResourcePreview/index.jsx
I did a couple of things in this. I am not sure how it was working, I guess the `* as ResourcePreview` but I updated the name ResourcePreview so it all matches. 
I also added the new truncate prop to allow for cell headers with wrapping text.
=> Add prop to remove the truncation on table cell headers

package.json, src/components/Pagination/index.jsx, src/components/Pagination/pagination.test.jsx, src/components/ResourceFooter/index.jsx, src/styles/scss/components/pagination.scss, src/templates/DatasetSearch/index.jsx
This will require an update to services (https://github.com/GetDKAN/data-catalog-services/pull/22) to work properly. I tried to standardize how we do pagination a bit, by always starting at 1 instead of 0.
=> Switch out Pagination component with USWDS based one

src/templates/APIPage/index.jsx, src/templates/Dataset/DatasetBody.jsx, src/templates/FilteredResource/FilteredResourceBody.jsx
Removes the schema from the instances of swagger on the /api page, dataset page and filtered resource page.
=> Removes schema from Swagger component calls

package.json, src/templates/Dataset/index.jsx, src/templates/FilteredResource/index.jsx, src/templates/Footer/index.jsx
This PR contains updates to work with tealium. For the dataset and filtered resource pages, the components now accept a new prop that will set the set the page title to the title from the metadata once retrieved. 
In the footer menu, the additional menu items have been updated to look for an onClick function and if it exists load a different menu link for the privacy settings feature.
=> Update components with tealium requirements

package-lock.json, package.json
There was an issue with one of the the child libraries `form-encode` used in Swagger UI that was breaking Safari. I am not sure why, but updating to latest version seems to have fixed it. I've also removed the unused Swagger code in https://github.com/GetDKAN/data-catalog-components/pull/160 that would continue to show the issue but the code isn't actually used on any site right now. 
Bumped to 1.4.0 since this requires a new version of data-catalog-components that removes a component.
=> Update swagger to see if fixes Safari regex error

package.json, src/styles/scss/templates/dataset.scss
The z-index was too high! Lowered it to 1 from 1000 so it would sit above the sort feature on the tables but not float above the drawer feature from CMS Design System.
=> Reduce Z-Index on resize handle

src/components/ResourcePreview/index.jsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/templates/FilteredResource/functions.js, src/templates/FilteredResource/index.jsx
This PR adds some customization options to the Dataset and Filtered Resource sections of the catalog. 
1. You can now override table classes in ResourcePreview with the customCustom classes prop.
2. A custom page title can be passed to the FilteredResource page
3. The custom columns function will now add the header and accessor using scheme description but these can be overwritten by passing a custom title. You can still pass in Cell prop to customize the table cell output.
=> Allow for custom updates to Resource Table and Filtered Resource titles

package.json, src/components/DatasetSearchFacets/index.jsx, src/styles/scss/components/dataset-search-facets.scss, src/templates/DatasetSearch/index.jsx
This PR addresses a couple of issues in the dataset explorer page and swaps out some components for upstream ones. 
- Adds an alert to the main section of the site when no results are found. 
- Updates the facets to display any facets selected, even if they have 0 results. This fixes an edge case where you could click two facets quickly that would return 0 results and 0 facets and the only option to fix the page was the clear all filters button
- Changes the facets container to the CMS Design System accordion which has native open and close feature with accessible focus traps and a built in scrollbar for overflow. Adding this allowed for removal of the show more button and we can now list all the facets without making the page grow too big. 
- Added the number of facets currently …
=> Add better no results messaging to search

package.json, src/components/DatasetDownloads/index.jsx
Most files have a 3 letter code like zip/or csv for the download link so this PR fixes some edge cases. 
On a page like: https://data.healthcare.gov/dataset/32ei-4grr, the type prop is set to something long without any break points for the browser to use so this PR adds the css class break-word to just add breaks when needed to fit the container.
=> Add break-word to dataset download link

package-lock.json, package.json, src/components/ResourceHeader/index.jsx, src/styles/scss/templates/dataset-search.scss, src/styles/scss/templates/filtered-resource.scss, src/styles/scss/templates/header.scss, src/styles/scss/templates/query-builder.scss, src/templates/FilteredResource/QueryTitle.jsx
Wraps the QueryBuilder filters in a div. This fixes an issue with layout when more than one filter is present, as the new button uses flex box and it was adding space between to all the filters. 
Adds some extra styling to address issues on Data.Healthcare which currently doesn't have the newest Design System loaded at the Drupal theme level.
=> Fix new flex styles on accordion titles

package-lock.json, package.json, src/styles/scss/templates/swagger.scss
If you shrink your browser down the text in the swagger component will shrink until it is one character per line.
=> Set min width and remove flex on swagger info at mobile

package-lock.json, package.json, src/templates/DatasetSearch/index.jsx
Currently when the search page loads, it runs the useEffect on page load which updates the browser history adding two instances to the browser. This update just checks to make sure the params in state do not match the `location.search` before firing so you don't get duplicate entries. 
Ticket number 10689
=> Fix search double back

src/components/NavLink/NavLink.scss, src/components/NavLink/index.jsx, src/templates/Header/header.scss
Note: Overrides on some downstreams mean this does not display in all apps.
Currently working on:
data.medicaid.gov
pfs-data
data.healthcare.gov
=> Persist underline for current page in header

src/components/SearchModal/index.jsx, src/styles/scss/index.scss, src/templates/Header/header.scss
I will probably have an update when I move this to data.healthcare but I wanted to start from a more base CMS Design System setup since it had the light gray header. I may just try to fix the styles downstream on that one. I added a heading to it since the new look isn't a full screen background with just the input but a more traditional modal looking element.
If you can check against PFS the same setup should then work for QIC and Data.Medicaid. Open Payments removed this feature and Data.Healthcare may remove it in a future round of design updates.
=> Update search modal styles and markup

src/components/Datatable/Datatable.jsx
I've added a new prop `loading` to DataTable, with default value "false", so no other downstreams will be affected unless we update them.
The loading state keeps the column headers intact, but replaces the body of the table with a spinner.
=> Add loading state to DataTable

src/components/MobileHeader/MobileHeader.jsx
WCMS-14341: When zoomed in past 400% on the desktop, users can now close the mobile menu by hitting the `escape` key.
=> WCMS-14341: Allow user to close menu with 'Escape' key.

src/templates/DatasetSearch/DatasetSearch.jsx, src/templates/DatasetSearch/datasetsearch.test.jsx
WCMS-14339: Adding necessary attributes to allow screen readers to be alerted of the search result outcome
=> WCMS-14339: Announce Data Search results to screen readers

package-lock.json, package.json, src/components/DatasetSearchListItem/index.jsx, src/templates/Dataset/DatasetBody.jsx, src/templates/FilteredResource/FilteredResourceBody.jsx
Adds DOMPurify and I am using it on each of the places we use dangerouslySetInnerHTML to prevent any possible XSS issues from the metadata forms.
=> Add dompurify to dangerouslysetinnerhtml

src/templates/APIPage/APIPage.jsx
The API docs page added extra `?` and `&` when not needed. To fix it I replaced the basic string with `qs.stringify` which will add those as needed. This would need to be tested as authenticated in Drupal and also using additional params for lower environments.
=> Add qs.stringfy to clean up api doc url

package-lock.json, package.json, src/templates/DatasetSearch/DatasetSearch.jsx, src/templates/DatasetSearch/dataset-search.scss, src/templates/DatasetSearch/datasetsearch.test.jsx
Added a prop to allow renaming of the "Tags" checkbox section.
Also adds the new search component as described by Kat in [the confluence page](https://confluence.cms.gov/pages/viewpage.action?spaceKey=ODCA&title=Technical+considerations+for+Data+Catalog+redesign)
Otherwise this is just swapping the 2 columns and a couple minor visual changes to match what was done on Open Payments.
=> WCMS-16250: Layout updates for redesign

package-lock.json, package.json, src/templates/Dataset/index.tsx
When no data dictionary tab exists, a 0 was appearing below the table. Returning `null` instead seems to make it go away.
=> Return null instead of 0 when no data dictionary tab

src/templates/APIPage/swagger-ui-overrides.scss
This adds back some missing CSS from PR #86
=> Fix Section Tag text in Swagger API

src/components/DatatableHeader/DatatableHeader.test.jsx, src/components/DatatableHeader/index.tsx, src/components/ResourceHeader/index.jsx
The aria-label attribute must contain the full button text exactly as written. When an interactive element has a valid aria-label, assistive tech like screen readers and voice control software will identify the button _only_ by the aria-label and they'll ignore all other text, including the visible text label. [https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html]
In this case we should remove the aria-label completely and edit the button text to "Download filtered data (CSV)", which is the more descriptive of the two options:
```
<a href="..." aria-label="Download filtered data (CSV)" class="..."><span class="..."><i class="fas fa-file-csv"></i> Export CSV</span></a>
```
=> Export CSV button: aria-label doesn't match visible text

src/components/DatasetSearchFacets/dataset_search_facets.test.jsx, src/components/DatasetSearchFacets/index.tsx
When a screen reader user encounters the Categories and Tags accordions, the button text and SVG title are both read aloud, and they seem to contradict.
For example, when the Categories accordion is open, a screen reader says, "Categories, Close, Expanded button".
The fix, is just passing a custom icon to the accordion component with aria hidden prop set as true.
=> Fixes aria-hidden on facet accordion to be hidden for improved accessibility

package-lock.json, package.json, src/components/DatasetSearchListItem/index.tsx, src/templates/DatasetSearch/DatasetSearch.tsx, src/templates/DatasetSearch/datasetsearch.test.jsx
I was having trouble building on Ubuntu from a missing `lightningcss` package. Running `npm update` seems to have fixed the issue for builds completing.
=> Fix TextTruncate props after npm update and types update

src/services/useMetastoreDataset/useMetastoreDataset.tsx, src/templates/Dataset/index.tsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/types/dataset.ts
**Description**
Dataset pages and the filtered view page (/data) display the modified date in the top right corner below the dataset title.
**AC**
Display the modified date in the top right corner of the dataset page as "Updated March 27, 2024"
Also display on the /data page.
**Before**
**After**
**To Test**
1. View a dataset page, ie: 
- http://localhost:3000/dataset/ebcfc16f-8291-4c61-82a4-055846d72f3a
- http://localhost:3000/dataset/ebcfc16f-8291-4c61-82a4-055846d72f3a/data
2. Confirm you see the modified date in the top right of the content region.
=> WCMS-19787 added modified date information to /data page

src/components/DatasetSearchListItem/index.tsx, src/components/Resource/index.tsx
This PR just sets the distribution's description to look like the dataset description. This is to help datasets like https://data.medicaid.gov/dataset/d30cfc7c-4b32-4df1-b2bf-e0a850befd77#overview
=> Show distribution descriptions like dataset descriptions

src/templates/DatasetSearch/DatasetSearch.tsx
An example of this would be visit https://data.medicaid.gov/datasets?page=5 and click on the `eligibility` facet. It is still trying to look at page 5. This is compared to https://data.healthcare.gov/datasets?page=5 and click on `Assisters`.
=> Reset search pagination on fulltext/facet change

src/components/Resource/Resource.test.jsx, src/components/Resource/index.tsx
1. visit http://localhost:3000/dataset/a217613c-12bc-5137-8b3a-ada0e4dad1ff#overview
2. compare to https://data.medicaid.gov/dataset/a217613c-12bc-5137-8b3a-ada0e4dad1ff#overview
3. verify visual changes
=> WCMS-20063 updates - increased icon size and added file extension to display text

package-lock.json, package.json, src/components/Resource/index.tsx, src/templates/Dataset/index.tsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/templates/FilteredResource/FilteredResourceDescription.jsx, src/templates/FilteredResource/filteredresource-description.test.jsx, src/templates/FilteredResource/index.jsx
This PR does the following:
1. Remove React Text Truncate which is no longer used
2. Add `withQueryProvider` to the FilteredResource template
3. Wrap Resource distribution description with a `div` instead of a `p`, since some descriptions contain multiple `p` tags already
4. Create a new FilteredResourceDescription component that will show distribution descriptions and if that doesn't exist the dataset.description. If nothing is passed, for initial renders it shows null until those are available. 
5. Adds some tests for the new component.
=> Filtered resource description fallback

package.json, src/services/useDatastore/useDatastore.jsx, src/templates/Dataset/index.tsx, src/templates/FilteredResource/FilteredResourceBody.jsx
=> Restore requireConditions functionality to useDatastore

src/components/DatasetDataDictionaryTab/index.tsx, src/templates/Dataset/index.tsx, src/types/dataset.ts
Can be enabled downstream by adding a "dataDictionaryCSV" prop to the <Dataset> component. Currently only enabled on medicaid.
=> WCMS-20265: Enable Data Dictionary CSV Downloads with a prop

src/components/DatasetTableTab/DatasetTableTab.test.jsx, src/components/DatasetTableTab/index.tsx, src/templates/Dataset/index.tsx, src/types/dataset.ts
The new prop is `dataDictionaryBanner` and should be added to the `<Dataset />` Template call in the downstream site
=> WCMS-21486: Add data dictionary info banner when data dictionaries are enabled and prop is passed

package-lock.json, package.json, src/components/DatasetTableTab/index.tsx, src/components/Datatable/Datatable.jsx, src/components/ResourcePreview/index.jsx, src/templates/Dataset/index.tsx, src/templates/FilteredResource/FilteredResourceBody.jsx
This PR wraps components in the /data route with context providers so that child components can still render. I will be working on a followup PR to properly migrate all the data structure on this route to the new context
=> Migrate /data route to react context

src/components/DataDictionaryTable/index.tsx, src/components/DatasetTableTab/index.tsx, src/templates/DatasetSearch/DatasetSearch.tsx
The pagination disabled bug seems to be a quirk/bug of the design system component - the renderHref prop needs to actually return something or else the Next and Previous buttons render as buttons instead of links, and their disabled styling isn't set up to render that correctly.
This PR also fixes a bug where page values on the /datasets page were not being respected by the app on a reload.
=> WCMS-19554: Fix pagination Bugs

src/components/Datatable/Datatable.jsx, src/components/ResourceFooter/index.jsx, src/components/ResourceHeader/index.jsx, src/components/ResourcePreview/index.jsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/templates/FilteredResource/filtered-resource.scss
Let me know if you need an alpha release.
This PR cleans up some unneeded code from the migration to the new state management. It also updates the loading states on the /data route to match the data table tab page. (While loading, a Spinner should appear in the data table, results text should not appear, and Pagination should not appear)
=> WCMS-22095: Clean up /data route components

src/components/DatasetDescription/dataset-description.test.jsx, src/components/DatasetDescription/index.tsx, src/templates/Dataset/index.tsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/templates/FilteredResource/FilteredResourceDescription.jsx, src/templates/FilteredResource/index.jsx, src/types/dataset.ts
Some of the datasets need descriptions to match the current conditions added when viewing the /data route. This PR adds two new properties to the FilteredResource template. One is dynamicDescription which is a boolean to let the description component know if it should update on any change of the page's data. The other is customDescription which is a function that takes the parameters dataset, distribution, and resource. This allows a custom function on the child site to control the description, like firing only on specific datasets and when certain conditions are met.
=> Add new dynamicDescription and customDescription to FilteredResource template

src/templates/Footer/index.jsx
Our sites are being flagged on Site Improve from the links in the footer having `http` instead of `https`. They are correctly redirected when you click on them, but this will help improve our score.
=> Make footer icon links https

src/templates/Header/index.tsx
This is on 3.6.2-alpha.1.
To test:
1. Update one of the sites with the new header to the new alpha version
2. Build the site
3. The header should work in desktop still
4. Shrink the site to mobile
5. Visit the /datasets page
6. Scroll to the bottom of the page and click a link
7. The site should no longer scroll back to the main menu button. 
8. You should also be able to interact with the dataset pages in mobile view too
=> Fix mobile scroll to to top bug

src/templates/FilteredResource/FilteredResourceBody.jsx
This update was made to the data and dataset search page, but didn't get applied to the filtered resource pages too.
=> Remove gray color on date to be more accessible

src/components/ResourcePreview/index.jsx
Testing steps with data.healthcare and npm workspace:
- Make sure data.healthcare is on `WCMS-23926` branch.
- Visit /ab-registration-completion-list or /ab-suspension-and-termination-list
- Click "Manage Columns"
- Modal should be populated. I don't think functionality is meant to be there yet but check with Andrew J.
=> WCMS-23926: Resource component fix for data.healthcare Manage Columns feature

package-lock.json, package.json, src/components/ApiDocumentation/index.jsx, src/templates/APIPage/APIPage.jsx, src/templates/APIPage/swagger-ui-overrides.scss
This PR adds the new Swagger UI Layout library and updates the info tags to use spans instead of pre and small elements. 
This can't be merged until the swagger ui layout release is made. When using an npm workspace, you should be able to clone https://github.com/GetDKAN/swagger-ui-layout/pull/2 and then run this against a site. It uses the Swagger plugin system to overwrite components during render so there is only config and css necessary to setup here.
=> Update swagger info tags using swagger-ui-layout

src/components/Datatable/datatable.scss
Updated the CSS selector - thead th div - in the datatable.scss file to change the cursor style from pointer to default. This adjustment ensures that table headers do not appear interactive when they are not intended to be clickable.
=> WCMS-23623: update cursor from pointer to defaut

src/templates/DatasetList/DatasetList.tsx
This moves the intro text variable into the main content area for the DatasetList component, which is currently only used on the What's New page. These changes will align the intro text styles with the [What's New design comps](https://www.figma.com/design/UeExz8CG4PKK4s84NmVIie/%22What-s-New-%22-Dropdown?node-id=35-1543&m=dev&focus-id=21-3956)
=> WCMS-25630: Move the intro text variable into the main content area

package-lock.json, package.json, src/assets/icons/searchItem.tsx, src/components/DatasetSearchListItem/dataset-search-list-item.scss, src/components/DatasetSearchListItem/datasetsearchlistitem.test.jsx, src/components/DatasetSearchListItem/index.tsx, src/components/LargeFileDialog/LargeFileDialog.test.js, src/templates/Dataset/index.tsx, src/templates/DatasetSearch/DatasetSearch.tsx
WCMS-25886: Improve UX for datasets that don't have a datastore table
- Updated Data Table links on dataset search page to display disabled tooltip for datasets that don't have a CSV.
- Updated Data Dictionary links on dataset search page to display disabled tooltip for datasets that don't have a data dictionary.
- Updated unit tests
1. Set up npm workspace with `cmsds-open-data-components` and the `healthcare` OD repo.
2. Checkout the PR branch (WCMS-25886-improve-ux-for-datasets-with-no-table) within the `cmsds-open-data-components` repo.
3. Spin up the environment.
4. Data Dictionary links are turned off on the dataset search page for data.healthcare. To turn them on to test, open `healthcare/docroot/frontend/src/templates/DatasetSearchPage/index.jsx` and add the …
=> WCMS-25886: Improve UX for datasets that don't have a datastore table

package-lock.json, package.json, src/components/DataTableToolbar/DataTableToolbar.scss, src/components/DisplaySettings/index.test.tsx, src/components/DisplaySettings/index.tsx, src/components/FilterDataset/index.tsx, src/components/FullScreenDataTable/index.tsx, src/components/ManageColumns/ManageColumns.jsx
Resolve an issues where toolbar button label text is missing in mobile and tablet views
Testing:
- Checkout branch in workspaces with a downstream data site
- Open dev tools and change screen size in responsive view to be less than 1024px
- Open voice over on MacOS or another screen reader if using a different operating system
- Tab through the dataset toolbar buttons and verify that the screen reader reads the button labels for 'Filter Dataset', 'Manage Columns', 'Display Settings', and 'Full Screen'
=> Resolve screen reader issue on dataset toolbar buttons
