src/components/DataTable/index.jsx, src/components/DataTableHeader/index.jsx, src/components/DataTableRowChanger/index.jsx, src/components/DataTableRowDetails/index.jsx, src/components/Pagination/index.jsx, src/index.js, src/styles/scss/components/index.scss, src/styles/scss/components/pagination.scss
This adds a pagination component using the usePagination service in dkan services. It has some css to compliment the cmd design system classes. It should work with both the search and dataset pagination. Since there isn't a design system mockup for how pagination will work, this may change some before final release.
=> Custom hook pagination

__mocks__/styleMock.js, package.json, src/components/DatasetSearchFacets/dataset_search_facets.test.jsx, src/components/DatasetSearchFacets/index.jsx, src/components/DatasetSearchListItem/datasetsearchlistitem.test.jsx, src/components/DatasetSearchListItem/index.jsx, src/components/Pagination/index.jsx, src/index.js, src/styles/scss/components/dataset-search-facets.scss, src/styles/scss/components/dataset-search-list-item.scss, src/styles/scss/components/index.scss, src/styles/scss/templates/dataset-search.scss, src/styles/scss/templates/index.scss, src/templates/DatasetSearch/datasetsearch.test.jsx, src/templates/DatasetSearch/index.jsx
This uses the new useSearchAPI hook to build and update the dataset search page.
=> Adds the components needed for dataset search pages

package.json, src/components/DatasetSearchListItem/index.jsx, src/index.js, src/templates/DatasetSearch/index.jsx, yarn.lock
This PR adds basic functionality to the library to allow for Search param parsing on the Dataset Search page.
=> Add Search URL reading to Dataset Search and export Search List Items from library

package.json, src/components/DataTableRowChanger/index.jsx, src/components/DatasetDownloads/index.jsx, src/components/DatasetSearchListItem/index.jsx, src/components/DatasetTags/index.jsx, src/components/Pagination/index.jsx, src/components/ResourceFilter/index.jsx, src/components/ResourceFooter/index.jsx, src/components/ResourceHeader/index.jsx, src/styles/scss/templates/dataset.scss, src/styles/scss/templates/filtered-resource.scss, src/styles/scss/templates/index.scss, src/templates/Dataset/index.jsx, src/templates/FilteredResource/index.jsx, yarn.lock
This is the first round of updates to get closer to UAT ready for the catalogs. There are a lot of style changes and a couple of feature additions:
- Updates the Filtered Resource to use the QS library instead of my custom search params
- Adds copy to clipboard on Filtered Resources
- Adds pagination to Dataset and Filtered Resource
- Adds row size changer to Filtered Resource
=> UAT Updates

package.json, src/templates/Footer/index.jsx
This updates the footer to account for fixes in the bug swatter board issue 69.
=> Update footer with some responsive bug fixes

package.json, src/components/ResourceHeader/index.jsx, src/components/ResourcePreview/index.jsx, src/index.js, src/styles/scss/templates/footer.scss, src/templates/APIPage/index.jsx, src/templates/Dataset/index.jsx, src/templates/DatasetSearch/index.jsx, src/templates/Footer/index.jsx, src/templates/PageNotFound/index.jsx, yarn.lock
There are some `parseInt()` in a couple of files. This was just an attempt to clean out some of the prop-type warnings/errors we were receiving in console.
=> Fixes Bug from the Bugswatter board and updates react to 17.x

package.json, src/templates/header/index.jsx, src/templates/mobile_header/index.jsx
This PR is to allow custom layout of the header and footer on sites that need it.
=> Updates to customize header and footer from the base design

package.json, src/components/DatasetAdditionalInformation/index.jsx
Fixes an issue with the additional table component breaking when optional fields were blank.
=> Fix error when optional additional information is not included with dataset

package.json, src/components/SearchModal/index.jsx, src/templates/header/index.jsx, src/templates/mobile_header/index.jsx
Update the Search Modal and header components to allow for toggling of inverse prop.
=> Inverse search modal

package.json, src/components/DataTableDensity/index.jsx, src/components/DatasetAdditionalInformation/index.jsx, src/components/DatasetSearchListItem/index.jsx, src/components/ResourceHeader/index.jsx, src/templates/Dataset/DatasetBody.jsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/templates/FilteredResource/index.jsx, yarn.lock
This update contains fixes for some site UAT bugs.
=> Random fixes for UAT

src/templates/mobile_header/index.jsx
=> WCMS-4633: mobile menu updates

package.json, src/components/DatasetSearchFacets/index.jsx, src/components/ResourceInformation/index.jsx, src/components/SearchModal/index.jsx, src/styles/scss/components/index.scss, src/styles/scss/components/resource-information-table.scss, src/templates/Dataset/DatasetBody.jsx, src/templates/DatasetSearch/index.jsx
On any dataset that displays a resource preview, this update adds a table with row/column counts.
=> Add Row/Count data to Dataset pages

package-lock.json, package.json, src/components/ResourceHeader/index.jsx, src/components/ResourcePreview/index.jsx
Using updates in https://github.com/GetDKAN/data-catalog-components/pull/158 and https://github.com/GetDKAN/data-catalog-services/pull/25 this adds some custom components to make the loading and no results state of the data table more user friendly.
=> Update datatable loading, no results, and header

package.json, src/templates/DatasetSearch/index.jsx
Set Dataset Search page h1 to a prop with default.
=> Add default prop for custom dataset search title

package.json, src/templates/Dataset/index.jsx, src/templates/FilteredResource/index.jsx, src/templates/PageNotFound/index.jsx
This PR updates the h1s on the 404 pages to use the ds-title like the rest of the site.
=> Update 404 titles

package-lock.json, package.json, src/components/ResourcePreview/index.jsx, src/styles/scss/templates/dataset.scss, src/styles/scss/templates/header.scss, src/templates/Dataset/DatasetBody.jsx, src/templates/Dataset/index.jsx, src/templates/DatasetSearch/index.jsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/templates/FilteredResource/index.jsx, src/templates/mobile_header/index.jsx
Updates the link color of top nav links when visited
Adds ability to change dataset search page order and the default page sort
Fix css to allow for resizing Resource Preview table columns and set max width to 84% of container div instead of the base 300px
=> Sprint 1.1 Updates

src/templates/DatasetSearch/index.jsx
Gives the option to hide the Sort By section on the dataset search page template.
=> Update dataset search sort params to allow customization

src/templates/header/index.jsx
Add prop to use custom classes for header.
=> Allow custom classes for header

package-lock.json, package.json, src/templates/Dataset/DatasetBody.jsx, src/templates/FilteredResource/functions.js
This PR adds the ability to override column display values by schema instead of hard coding each specific column accessor. It is backwards compatible as any accessor passed in will be used with the schema as a default fall back.
=> Allow for schema overrides in custom column function

src/index.js, src/templates/FilteredResource/functions.js
This updates the QueryBuilder to work with the new Starts With and Contains operators from DKAN. It also allows for the query builder to be added to custom pages.
=> Export QueryBuilder and update operators

src/components/Datatable/Datatable.jsx
Fix accidental sort clicks when resizing, and improve resizing behaviour.
=> Table upgrades

src/components/Datatable/Datatable.jsx, src/components/Datatable/FixedSizeTHead.jsx, src/components/Datatable/TruncatedResizeableTHead.jsx, src/components/Datatable/datatable.scss, src/components/ResourcePreview/index.jsx
This would be best tested against data.healthcare 2.x branch as the AB List templates use the override feature.
=> Redo header truncate to work with sort button

.babelrc, package-lock.json, package.json, src/components/LargeFileInfo/index.tsx, src/components/PageHeader/index.tsx, src/components/SearchButton/index.tsx, src/templates/DatasetSearch/DatasetSearch.jsx, src/templates/DatasetSearch/dataset-search.scss
Note that I have added the large file dialog display as a prop, however any downstream site using it will need to implement the `/about/software-specs-and-limits` route. I will make a separate ticket to implement this route in the upstream so that it can be more easily implemented downstream.
`3.0.0-alpha.3` has been released to help test this PR.
=> WCMS-16249: Dataset redesign - Header

package-lock.json, package.json, src/templates/FilteredResource/QueryRow.jsx
alpha.11 has been released to npm for testing
=> WCMS-17459: Fix Dropdown render

src/components/DatasetSearchFacets/index.tsx
I haven't done a release on npm as we have a few divergent PRs and it seemed messy.
=> WCMS-17064: Fix Facet error states on explorer page

package-lock.json, package.json, src/templates/FilteredResource/QueryBuilder.jsx, src/templates/FilteredResource/query-builder.scss
3.0.0-alpha.9 is published for testing.
=> WCMS-17447: Fix select overflow render within Accordion

package-lock.json, package.json, src/components/Datatable/Datatable.jsx, src/components/Datatable/TruncatedResizeableTHead.jsx, src/components/Datatable/datatable.scss
2.1.5-alpha.1 is released to npm for testing
=> WCMS-14283: Improve keyboard accessibility for data table

src/components/ApiDocumentation/index.jsx, src/templates/APIPage/APIPage.jsx, src/templates/APIPage/swagger-ui-overrides.scss
WCMS-9877: Proposed changes fix color contrast issues noted in WCMS-6698 and WCMS-8942.
=>  WCMS-9877: swagger ui a11y fixes (against 3x branch)

package-lock.json, package.json, src/components/ApiDocumentation/index.jsx, src/templates/APIPage/APIPage.jsx, src/templates/APIPage/swagger-ui-overrides.scss
WCMS-9877: Proposed changes fix color contrast issues noted in WCMS-6698 and WCMS-8942.
=> WCMS-9877: swagger ui a11y fixes (against 2x branch)

__mocks__/fileMock.js, __mocks__/mockLinks.js, src/components/MobileHeader/MobileHeader.jsx, src/components/MobileHeader/MobileHeader.test.jsx
WCMS-18024: Add trap focus when mobile menu is open.
=> WCMS-18024: mobile menu trap focus

package-lock.json, package.json, src/templates/FilteredResource/QueryRow.jsx, src/templates/FilteredResource/query-builder.scss
Fix for extra double arrow icon in the date-picker, and pixel shift on date picker field in the QueryRow
Can be tested with data.medicaid at url: `dataset/4a00010a-132b-4e4d-a611-543c9521280f/data`
=> WCMS-0000: Fix dropdown and datepicker bugs

package.json, src/templates/APIPage/APIPage.jsx, src/templates/APIPage/swagger-ui-overrides.scss, src/templates/APIPage/swagger.scss
3.0.0-alpha.23 released for testing
=> WCMS-17599: Add horizontal scroll to swagger

package.json, src/templates/Dataset/index.tsx, src/templates/Header/header.scss
=> WCMS-17641: Title and focus state fixes

package-lock.json, package.json, src/components/DataTableRowChanger/datatablerowchanger.test.jsx, src/services/useDatastore/useDatastore.jsx, src/templates/Dataset/index.tsx
=> 3.0: Hide datatable tab when not used, and fix bad datastore call

src/templates/APIPage/swagger-ui-overrides.scss
This adds back some missing CSS from PR https://github.com/GetDKAN/cmsds-open-data-components/pull/86
=> Fix Section Tag text in Swagger API

src/components/Resource/Resource.scss, src/components/Resource/index.tsx
only the csv distributions show row and column counts in the overview tab.
=> only the csv distributions show row and column counts in the overview tab

src/components/DatasetTableTab/DatasetTableTab.test.jsx, src/components/QueryBuilder/QueryBuilder.test.jsx, src/templates/FilteredResource/QueryTitle.jsx
updated accordion text label to be more descriptive for screen readers.
**Before**
**After**
**Before**
**After**
=> WCMS-19144 updated accordion text label to be more descriptive for screen readers

package.json, src/components/DatasetTableTab/index.tsx, src/components/DatatableHeader/index.tsx
Hides the results # UI and the table Pagination while the resource is in a loading state
=> WCMS-19766: Clear UI elements when resource is loading

package-lock.json, package.json, src/components/DataTablePageResults/DataTablePageResults.tsx, src/components/DataTableRowChanger/index.tsx, src/components/DesktopHeader/DesktopHeader.jsx, src/components/Hero/index.jsx, src/components/MobileHeader/MobileHeader.jsx, src/components/NavBar/Navbar.tsx, src/components/NavLink/index.tsx, src/components/QueryBuilder/index.tsx, src/components/ResourcePreview/index.jsx, src/components/SearchModal/index.jsx, src/components/TransformedDate/index.jsx, src/templates/APIPage/APIPage.jsx, src/templates/DatasetSearch/DatasetSearch.tsx, src/templates/FilteredResource/FilteredResourceBody.jsx, src/templates/FilteredResource/QueryBuilder.jsx, src/templates/Footer/index.jsx, src/templates/Header/Header.jsx, src/templates/SpecsAndLimits/index.tsx
3.4.3-alpha.1 released for testing
To test: Install the above alpha on a downstream site and run the react app. Verify everything works as expected.
=> WCMS-21553: update package dependencies to address warnings

src/components/Datatable/datatable.scss
3.6.1-alpha.1 is released for testing
=> WCMS-22565: Fix scrollable full screen mode dialog

src/components/DatasetSearchListItem/dataset-search-list-item.scss, src/components/DatasetSearchListItem/index.tsx, src/components/LargeFileDialog/index.tsx
See: https://jira.cms.gov/browse/WCMS-24523
All should work as described in the ticket.
=> Refactor dataset search list markup

package-lock.json, package.json
Version 4.0.2 is blocked form publishing in npm. Updating to 4.0.3 instead
=> Update version number to 4.0.3
